service: remotepixel-bot

provider:
  name: aws
  runtime: python3.6
  stage: ${opt:stage, 'production'}

  region: us-west-2

  iamRoleStatements:
  -  Effect: "Allow"
     Action:
       - "s3:GetObject"
     Resource:
       - "arn:aws:s3:::landsat-pds/*"

  environment:
    GDAL_CACHEMAX: 75%
    GDAL_TIFF_OVR_BLOCKSIZE: 512
    VSI_CACHE: TRUE
    VSI_CACHE_SIZE: 536870912
    GDAL_DISABLE_READDIR_ON_OPEN: true
    CPL_VSIL_CURL_ALLOWED_EXTENSIONS: ".TIF,.ovr"
    C_KEY: ${file(.config.json):consumer_key}
    C_SECRET: ${file(.config.json):consumer_secret}
    A_KEY: ${file(.config.json):access_key}
    A_SECRET: ${file(.config.json):access_secret}

  deploymentBucket: remotepixel-${self:provider.region}

package:
  artifact: package.zip

functions:
  bot:
    handler: cloud_bot.handler.handler
    memorySize: 1536
    timeout: 40
    events:
      - schedule: rate(2 hours)
